extend OCL to support service actions.
eclipse-xpanse/xpanse-samples pull request #14
Opened 2024-12-17 12:04 UTC by WangLiNaruto

eclipse-xpanse/xpanse#2207

2024-12-17 12:27 UTC, yuanxiaojun987 commented
LGTM

2024-12-17 12:27 UTC, Alice1319 commented
LGTM

2024-12-17 13:05 UTC, swaroopar requested changes

2024-12-17 13:05 UTC, swaroopar commented on middleware/HuaweiCloud-Kafka-autofill.yml
> +      - name: kafka_cfg_message_max_bytes
we need some other action parameters which are really valid for upgrade of a kafka broker.

2024-12-18 01:02 UTC, wuzhuanhong commented
LGTM

2024-12-18 05:33 UTC, profoundwu commented
LGTM

2024-12-18 06:28 UTC, baixinsui commented
LGTM

2024-12-18 07:56 UTC, swaroopar approved these changes
LGTM

2024-12-18 08:05 UTC, merged